"""`custodian parse`: batch-parses corpus PDFs through MinerU into `parsed/<doc_id>/` (for `custodian
index` to build a database from).

Productized from the engine-era scripts/{parse_batch,mineru_client}.py. Reads a manifest CSV
(generated by scripts/select_sample.py), batches calls to the MinerU v4 API by (api_key,
language), concurrently uploads, polls, and downloads+unzips into dest/<doc_id>/. Resumable
(already-parsed docs are skipped). The MinerU token is read from custodian/.env
(MINERU_TOKEN_A/B/C, in the same .env as the rest of the config).

Flow (https://mineru.net/apiManage/docs): POST file-urls/batch -> PUT to each presigned URL
(raw binary, no Content-Type, which starts parsing automatically) -> poll GET
extract-results/batch/{id} -> download full_zip_url and unzip it.
"""
from __future__ import annotations

import csv
import io
import os
import time
import zipfile
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

from . import config

BASE = "https://mineru.net"
DONE_STATES = {"done", "failed"}


def _tokens() -> dict:
    config.load_env()   # load custodian/.env -> MINERU_TOKEN_*
    return {k: os.environ.get(f"MINERU_TOKEN_{k}") for k in ("A", "B", "C")}


def _headers(token: str) -> dict:
    return {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}


def _create_batch(token, files, language=None, model_version="vlm", enable_formula=True, enable_table=True):
    """files: [{"name","data_id", optional "page_ranges"}]. Returns (batch_id, file_urls) (in the same order as files)."""
    import requests
    body = {"files": files, "model_version": model_version,
            "enable_formula": enable_formula, "enable_table": enable_table}
    if language:
        body["language"] = language
    r = requests.post(f"{BASE}/api/v4/file-urls/batch", headers=_headers(token), json=body, timeout=60)
    r.raise_for_status()
    j = r.json()
    if j.get("code") != 0:
        raise RuntimeError(f"create_batch failed: {j}")
    return j["data"]["batch_id"], j["data"]["file_urls"]


def _upload(file_url, path, retries=3) -> bool:
    """PUT the file to the presigned URL (must not include a Content-Type header)."""
    import requests
    for attempt in range(retries):
        try:
            with open(path, "rb") as f:
                r = requests.put(file_url, data=f, timeout=600)
            r.raise_for_status()
            return True
        except Exception as e:
            if attempt == retries - 1:
                print(f"  ! upload failed {Path(path).name}: {e}", flush=True)
                return False
            time.sleep(2 * (attempt + 1))
    return False


def _poll_batch(token, batch_id) -> list:
    import requests
    r = requests.get(f"{BASE}/api/v4/extract-results/batch/{batch_id}", headers=_headers(token), timeout=60)
    r.raise_for_status()
    j = r.json()
    if j.get("code") != 0:
        raise RuntimeError(f"poll failed: {j}")
    return j["data"].get("extract_result", [])


def _download_and_extract(zip_url, dest_dir, retries=3):
    import requests
    dest_dir = Path(dest_dir)
    dest_dir.mkdir(parents=True, exist_ok=True)
    for attempt in range(retries):
        try:
            r = requests.get(zip_url, timeout=600)
            r.raise_for_status()
            with zipfile.ZipFile(io.BytesIO(r.content)) as z:
                z.extractall(dest_dir)
            return sorted(p.name for p in dest_dir.iterdir())
        except Exception as e:
            if attempt == retries - 1:
                print(f"  ! download failed {zip_url}: {e}", flush=True)
                return None
            time.sleep(3 * (attempt + 1))
    return None


def _already_done(dest: Path, doc_id: str) -> bool:
    d = dest / doc_id
    return d.exists() and any(d.rglob("*content_list.json"))


def run_parse(manifest: str, dest: str, corpus_root: str,
              poll_secs: int = 15, max_poll_min: int = 60) -> int:
    """Batch-parses according to the manifest -> dest/<doc_id>/. corpus_root resolves the
    manifest's relative corpus_path entries. Returns the number of documents parsed successfully."""
    manifest_p, dest_p, corpus_p = Path(manifest), Path(dest), Path(corpus_root)
    if not manifest_p.exists():
        raise SystemExit(f"manifest does not exist: {manifest_p} (generate sample_manifest.csv with scripts/select_sample.py)")
    tokens = _tokens()
    rows = list(csv.DictReader(open(manifest_p, encoding="utf-8")))
    todo = [r for r in rows if not _already_done(dest_p, r["doc_id"])]
    print(f"{len(rows)} docs total, {len(rows) - len(todo)} already parsed, {len(todo)} to do", flush=True)
    if not todo:
        print(f"all already parsed -> {dest_p}", flush=True)
        return 0
    missing = sorted({r["api_key"] for r in todo} - {k for k, v in tokens.items() if v})
    if missing:
        raise SystemExit(f"missing MINERU_TOKEN_{' / MINERU_TOKEN_'.join(missing)} (put it in custodian/.env).")

    # Group into batches (by key + language), create each batch, and upload concurrently
    groups: dict = {}
    for r in todo:
        groups.setdefault((r["api_key"], r["language"]), []).append(r)
    batches = []
    for (key, lang), grp in groups.items():
        files = []
        for r in grp:
            f = {"name": r["doc_id"] + ".pdf", "data_id": r["doc_id"]}
            if r.get("page_ranges"):
                f["page_ranges"] = r["page_ranges"]
            files.append(f)
        print(f"submit batch key={key} lang={lang} files={len(files)}", flush=True)
        batch_id, urls = _create_batch(tokens[key], files, language=lang)

        def _up(pair):
            r, url = pair
            # corpus_path may use Windows-style backslashes -> normalize for WSL/Linux compatibility
            return _upload(url, corpus_p / r["corpus_path"].replace("\\", "/"))
        with ThreadPoolExecutor(max_workers=8) as ex:
            list(ex.map(_up, zip(grp, urls)))
        batches.append({"key": key, "batch_id": batch_id,
                        "name2doc": {r["doc_id"] + ".pdf": r["doc_id"] for r in grp}})
        print(f"  uploaded {len(grp)} files, batch_id={batch_id}", flush=True)

    # Poll until complete
    results: dict = {}
    pending = {b["batch_id"]: b for b in batches}
    deadline = time.time() + max_poll_min * 60
    while pending and time.time() < deadline:
        time.sleep(poll_secs)
        for batch_id, b in list(pending.items()):
            try:
                res = _poll_batch(tokens[b["key"]], batch_id)
            except Exception as e:
                print(f"  poll err {batch_id}: {e}", flush=True)
                continue
            done_here = 0
            for st in res:
                doc_id = b["name2doc"].get(st["file_name"])
                if not doc_id or doc_id in results:
                    if st["state"] in DONE_STATES:
                        done_here += 1
                    continue
                if st["state"] == "done":
                    results[doc_id] = {"state": "done", "zip_url": st["full_zip_url"]}
                    done_here += 1
                elif st["state"] == "failed":
                    results[doc_id] = {"state": "failed", "zip_url": "", "err": st.get("err_msg", "")}
                    done_here += 1
            print(f"  [{b['key']}] {batch_id[:8]} {done_here}/{len(b['name2doc'])} done", flush=True)
            if done_here >= len(b["name2doc"]):
                del pending[batch_id]

    # Download and unzip concurrently
    done_docs = [(d, r["zip_url"]) for d, r in results.items() if r["state"] == "done"]
    print(f"\ndownloading {len(done_docs)} zips -> {dest_p} ...", flush=True)

    def _dl(pair):
        doc_id, url = pair
        return doc_id, _download_and_extract(url, dest_p / doc_id) is not None
    with ThreadPoolExecutor(max_workers=8) as ex:
        for doc_id, ok in ex.map(_dl, done_docs):
            print(f"  {'OK ' if ok else 'ERR'} {doc_id}", flush=True)

    ok = sum(1 for r in results.values() if r["state"] == "done")
    fail = sum(1 for r in results.values() if r["state"] == "failed")
    print(f"\nDONE -> {dest_p}  {ok} ok, {fail} failed, {len(todo) - len(results)} timed-out", flush=True)
    return ok
